# What is NumPy (Numerical Python)? 

NumPy is the fundamental package for scientific computing in Python.

--- linear algebra, integration and image processing etc.

Almost every field of science and engineering

It is a Python library that provides a multidimensional array object.

It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers

![alt text](numpy-multidimensional.png "Title")

#### Python Libraries dependenant on Numpy

![alt text](numpy.png "Title")

# The Basics

In [3]:
import numpy as np

Initialization

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray


In [20]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [9]:
# 2D Array

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3D Array
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(c)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
# Get array dimension
a.ndim

1

In [17]:
# Get Shape
a.shape

(3,)

In [18]:
# Get Type
a.dtype

dtype('int32')

In [21]:
# Get total size
a.nbytes

6

# Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

Get the first element from the following array:



In [9]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [22]:
# Get a specific element [r, c]

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('2nd element on 1st row: ', arr[0] [1])

print('Last element from 2nd dim: ', arr[1, -1])

2nd element on 1st row:  2
2nd element on 1st row:  2
Last element from 2nd dim:  10


In [23]:
# Get a specific row, Slicing array
arr[0, :]

array([1, 2, 3, 4, 5])

In [24]:
# Get a specific column
arr[:, 2]

array([3, 8])

In [25]:
#[startindex:endindex:stepsize]
arr[0, 1:-1:2]

array([2, 4])

# Modifying Arrays

In [27]:
arr[0,1] = 22
print(arr)

[[ 1 22  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
arr[:,2] = 10
print(arr)

[[ 1 22 10  4  5]
 [ 6  7 10  9 10]]


In [30]:
arr[:,2] = [1,2]
print(arr)

[[ 1 22  1  4  5]
 [ 6  7  2  9 10]]


In [31]:
# 3D Arrays.
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
#Get Elements
b[0, :]

array([[1, 2],
       [3, 4]])

In [36]:
# Modify
b[0, :] = [[2,1], [4,3]]
print(b)

[[[2 1]
  [4 3]]

 [[5 6]
  [7 8]]]


# Initializing Different Types of Arrays

In [37]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [43]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [44]:
# Any other number (full_like)
a = np.array([[1,2],[1,2]])
np.full_like(a, 4)

array([[4, 4],
       [4, 4]])

In [45]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.91265432, 0.46463086],
       [0.63165182, 0.79653653],
       [0.46625882, 0.87182273],
       [0.64835879, 0.90472895]])

In [46]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-4,  0,  2],
       [ 2,  1, -1],
       [ 6, -1, -1]])

In [47]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
# Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [54]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


![alt text](matrix_to_build.png "Title")

In [56]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [57]:
z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [58]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [60]:
# Use copy function
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


# Mathematics

In [61]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [62]:
a + 2

array([3, 4, 5, 6])

In [63]:
a - 2

array([-1,  0,  1,  2])

In [64]:
a * 2

array([2, 4, 6, 8])

In [65]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [66]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [67]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [68]:
# Take the cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [71]:
# Matrix multiplication

a = np.ones((2,2))
print(a)

#Column of the matrix should be equal to row of the second matrix

b = np.full((2,2), 2)
print(b)

np.matmul(a,b)

[[1. 1.]
 [1. 1.]]
[[2 2]
 [2 2]]


array([[4., 4.],
       [4., 4.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [72]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.min(stats, axis=1) #row wise

array([1, 4])

In [75]:
np.max(stats, axis=1)

array([4, 5, 6])

In [ ]:
np.sum(stats, axis=0)

# Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

# Miscellaneous

In [ ]:
# Load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

In [ ]:
# Boolean Masking and Advanced Indexing
(~((filedata > 50) & (filedata < 100)))

# Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [15]:
#Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError

ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [16]:
#A non integer string like 'a' can not be converted to integer (will raise an error):

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [17]:
#Change data type from float to integer by using 'i' as parameter value:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# NumPy Array Reshaping
# Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

# Reshape From 1-D to 2-D


In [33]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D


In [34]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
